language: php
php:
  - 5.6
  - 7
sudo: false
branches:
  only:
    - master
    - develop
    - /v\d+\.\d+\.\d+?.*/
env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=inc@2inc.org
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=inc@2inc.org
    - secure: "RoG7GNdWAzbVhOrCdRkohAKk2nT8cja3X80f9ZnCOgqn3YuHk23Y3NJ4U/uwROsrRV//M7w1a5Gg1h4kMiCZxKmU4zCyOdI4bpl68tKSbNroLgxFQL43jfEXlnv4b4O0+hU0HpzpR/wX7v0jW6T0EkekRRRwh1lHv/k0YrUXMAyRGyZehFuDkqIlI73yiz7m6UB3HD7T0nlc3MWowSroLeiBtZUUI+D+PNJkHpCG9hOeZ1aCgYI3uiYF/YpIE0tlJJfRoWmQ4mwW2ZN0SJABvzGAIPAhELoCVG7uYipq9tr3eHYmjEuKeL7dIqGkj3KitJkA40PXxLTx+ocvYYntqjrUO62sw/+AjZC34ljs41+6DeqZAGsKEC5b6zBtTuuZBXUrFuYybDqxFpYl/Jc2gzjPmcqtibq+t3nmXDZqEuxYii2XKwMuM0l/wXXrQNH54gQgzNebFit98EKrWG/Ey3GdleL1XXNJ2WkZQAzdlcp9xfQapqn6pGvTsDt/y80gVx+zd+pGU+RyHfJsXAaMZZd9LKKqabE8+iXfjoU9yipvrDHqNip3ZD21FZA8mw2jpOf6PVXfaQ9UDHQIC1Srdnr6tmB9cDzqJoddUhbugm1JC/kG23NrHnV19Zdmj/4cMajfxbIaIKQc5EPSvvt6bMyTHkF7aO66nJye9i6GXwM="
cache:
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache
install:
  - composer install
  - nvm install 6
  - npm install
script:
  - npm run gulp build
  - ls -la style.css
  - composer test
after_success:
  - bash ./app/bin/wprepository.sh
before_deploy:
  - rm -rf wprepository
  - npm run zip
deploy:
  provider: releases
  file: mimizuku.zip
  on:
    tags: true
    repo: inc2734/mimizuku
